// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

import (
	"gopkg.in/validator.v2"
)

type Request struct {
	MaxLength string `json:"maxLength" validate:"nonzero"`
	MinLength string `json:"minLength" validate:"nonzero"`
	Required  string `json:"required" validate:"nonzero"`
	Type      string `json:"type" validate:"nonzero"`
}

func (s Request) Validate() error {

	return validator.Validate(s)
}
