// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package api

import (
	"net/http"

	"github.com/gorilla/mux"
)

// OnboardInterface is interface for /onboard root endpoint
type OnboardInterface interface { // Post is the handler for POST /onboard
	Post(http.ResponseWriter, *http.Request)
}

// OnboardInterfaceRoutes is routing for /onboard root endpoint
func OnboardInterfaceRoutes(r *mux.Router, i OnboardInterface) {
	r.HandleFunc("/onboard", i.Post).Methods("POST")
}
